#!/bin/bash
alias ll='ls -l'
alias showFiles='defaults write com.apple.finder AppleShowAllFiles YES; killall Finder /System/Library/CoreServices/Finder.       app'
alias hideFiles='defaults write com.apple.finder AppleShowAllFiles NO; killall Finder /System/Library/CoreServices/Finder.app'
alias reload='. ~/.bash_profile'
# WORKFLOW #
alias v='vim'
alias v.='vim .'
alias installVundlePlugins='vim +PluginInstall +qall'
alias hosts='sudo vim /etc/hosts'
alias ˜='cd ~/'
alias .1='cd ..'
alias .2='cd ../..'
alias .3='cd ../../..'
alias .4='cd ../../../..'
alias .5='cd ../../../../..'
alias .6='cd ../../../../../..'
alias .7='cd ../../../../../../..'
alias .8='cd ../../../../../../../..'
alias .9='cd ../../../../../../../../..'
# GIT #
alias got='git'
alias gut='git'
alias gits='git'
alias st='git status'
alias glg='git lg -50'
alias gco='git co'
alias gcm='git co master'
alias gbr='git br'
alias gab='git br -a'
alias gba='gab'
alias gpl='git co master && git pull origin master'
alias glp='gpl'
