# -*- mode: ruby -*-
# vi: set ft=ruby :
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "http://renatoluna.com/labs/environments/package.box"
  config.vm.forward_port "http", 80, 8080
end
